#!/bin/bash

# svn configuration

tar xf /home/cesm/svn_config/subversion.tar

# Specify number of processors per node

export CESM_PES=16

sed -i -e "s/\$CESM_PES/$CESM_PES/g" /home/cesm/.cime/config_machines.xml 

# Get VR-CESM code

## clone cesm 2.2.beta01

git clone -b cesm2_2_beta01 https://github.com/ESCOMP/CESM.git vr-cesm

cd vr-cesm

# Get all components

./manage_externals/checkout_externals

#####################
# Fix ar problem
sed -i.bak 's/# ARCHIVE COMMAND SIMILAR ACROSS ALL PLATFORMS/AR="$AR cq"/' ./cime/src/externals/mct/configure  

#####################


## copy vr-cesm specific files

export CESM_HOME=/home/cesm/vr-cesm

cp /home/cesm/vr_cesm_config/config_grids_common.xml       \
   $CESM_HOME/cime/config/cesm/.
cp /home/cesm/vr_cesm_config/config_grids.xml              \
   $CESM_HOME/cime/config/cesm/.
cp /home/cesm/vr_cesm_config/horiz_grid.xml                \
   $CESM_HOME/components/cam/bld/config_files/.
cp /home/cesm/vr_cesm_config/namelist_defaults_cam.xml     \
   $CESM_HOME/components/cam/bld/namelist_files/.
cp /home/cesm/vr_cesm_config/namelist_defaults_ctsm.xml    \
   $CESM_HOME/components/clm/bld/namelist_files/.
cp /home/cesm/vr_cesm_config/namelist_definition_ctsm.xml  \
   $CESM_HOME/components/clm/bld/namelist_files/.

# Create new case

cd cime/scripts

./create_newcase --case /home/cesm/cases/vr-cesm \
    --compset HIST_CAM60_CLM50%BGC_CICE%PRES_DOCN%DOM_MOSART_CISM2%NOEVOLVE_SWAV \
    --res ne0uoslone30x8_ne0uoslone30x8_mt12 --machine espresso --run-unsupported 

cd /home/cesm/cases/vr-cesm                        

./case.setup

./xmlchange EPS_AAREA=0.001
./xmlchange ATM_NCPL=144
 
cat >> user_nl_cam << EOF
se_nu_top=1e5
se_nu=8e-8
se_nu_div=15.8e-8
se_nu_p=8e-8
se_hypervis_scaling=3.2
se_hypervis_power=0
se_hypervis_subcycle=6
se_nsplit=6
se_hypervis_on_plevs=.false.
use_gw_rdg_beta=.false.
use_gw_oro=.true.
cld_macmic_num_steps=1
 
nhtfrq(1) = -24
EOF
 
cat >> user_nl_clm << EOF
hist_nhtfrq = -24
EOF
 
./xmlchange STOP_N=1
./xmlchange STOP_OPTION=ndays
 
./case.build

./case.submit

mkdir -p /home/cesm/archive/cases

cp -R /home/cesm/cases/vr-cesm /home/cesm/archive/cases/.
